config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'categories#index'
  resources :posts
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @posts = @category.posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<% @categories.each do |c| %>
  <h3><%= link_to c.name, category_path(c) %></h3>
<% end %>

app/views/categories/show.html.erb
<h4 class="text-center"><%= @category.name %></h4>

<% @posts.each do |post|%>
  <h4><%= link_to post.title, post_path(post) %></h4>
<% end %>

app/views/comments/_comment.html.erb
<div class="tab-content">
  <div class="tab-pane active" id="comments-logout">
    <ul class="media-list">
      <li class="media">
        <div class="media-body">
          <div class="well well-lg">
            <h4 class="media-heading text-uppercase reviews"><%= name %> </h4>
            <p class="media-comment">
              <%= raw content %>
            </p>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html dir="rtl">
  <head>
    <title>Ourway</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'bootstrap.rtl.min', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <h4 class="text-center"><%= link_to "الرئيسية", root_path %></h4>
    <%= yield %>
  </div>
  </body>
</html>

app/views/posts/index.html.erb
<%#= @title.encode!('windows-1256') %>
<%# @page.children.each do |c| %>
  <%#= c.at_css('a.username > strong').text.encode!('windows-1256') unless c.at_css('a.username strong').nil? %>
<!--  </br>-->

  <%#= raw c.at_css('blockquote.postcontent') %>

<%# end %>
<%= @posts.count %>
</br>
<% @posts.each do |post| %>
  <%= link_to post.title, post_path(post) %></br>
<% end %>

app/views/posts/show.html.erb
<%= stylesheet_link_tag 'bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>

<h4 class="text-center"><%= link_to @post.category.name, category_path(@post.category) %></h4>
<h4 class="text-center"><%= @post.title %></h4>

<div class="row">
  <div class="col-sm-12" id="logout">
    <div class="comment-tabs">
      <div class="tab-pane active" id="comments-logout">
        <ul class="media-list">
          <li class="media">
            <div class="media-body">
              <div class="well well-lg">
                <h4 class="media-heading text-uppercase reviews"><%= @post.user_name %> </h4>
                <p class="media-comment">
                  <%= raw @post.content %>
                </p>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="row align-items-center">
  <div class="col">
    <div class="comment-tabs">
      <ul class="nav nav-tabs" role="tablist">
        <li class="active"><a href="#comments-logout" role="tab" data-toggle="tab"><h4 class="reviews text-capitalize">التعليقات</h4></a></li>
      </ul>
      <% @post.comments.each do |comment| %>
        <%= render partial: comment, locals: {name: comment.user_name, content: comment.content} %>
      <% end %>
    </div>
  </div>
</div>